### PR TITLE
Web extebosion

### PR DESCRIPTION
**Pull request by chengjinshengtaichanyejituan**

### CODE REVIEW

**Comment by garak** [comment]
I'm wondering: is there a way to test a WebExtension-compatible version of Web Developer on Firefox?

**Comment by Cosmodor** [comment]
yes, there is. https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Debugging explains how to run the debug. If you have already downloaded and compiled the source code, then you have just to:
1) open about:debugging in a new tab in firefox
2) click on Enable add-on debugging
3) select the file manifest.json from build/firefox
4) "enjoy" debug !

**Comment by garak** [comment]
With "testing" I meant simply try. Can you point me to the correct way to accomplish "download & compile source code"?

**Comment by markvantilburg** [comment]
With 57 coming next week, how is this going?

**Comment by Cosmodor** [comment]
@garak I can list all the linux commands to achieve the compile section (the download section you can choose between git clone or download the zip, then extract in a folder :D)
0) sudo su
1) apt install npm
2) npm install --global gulp-cli
2) npm install gulp -D
3) apt install nodejs-legacy
4) cd <folder_where_you_stored_the_source_code> (ex. cd /home/test/firefox_addon/firefox-webdeveloper/web-developer-web-extension) -- inside this folder you'll find a file called gulpfile.js
5) gulp firefox (NOTE: at this point I found a problem with folders and missing files, but resolved with gulp initialize-firefox-build before launching this command)
6) now you'll find a folder called build inside the "web-developer-web-extension" (using my example), that you have to use later (to be more specific, the folder you'll use is called firefox, inside build)
7) use instructions in my previous comment ;)

**Comment by garak** [comment]
@Cosmodor that's great, but I'd like to avoid installing npm on my system. I guess you compiled on a 64-bit Linux, can you share your compiled code? TIA

**Comment by Cosmodor** [comment]
@garak yes, compiled on 64bit, here's the webextension https://github.com/Cosmodor/test/blob/master/web-developer-firefox.zip

**Comment by chrispederick** [comment]
Sorry for the silence on this pull request, but the WebExtension version of the extension is now live: https://addons.mozilla.org/en-US/firefox/addon/web-developer/

I need to do some Git cleanup as all this work was done on a separate branch that needs merging back into master, but I'm hoping to get all that tided up soon. I'm going to close this PR out now.

**Pull request closed without merging**
